export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const GET_INVENTORY_BEGIN = "GET_INVENTORY_BEGIN";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_INVENTORY_ERROR = "GET_INVENTORY_ERROR";

export const GET_TRANSACTION_BEGIN = "GET_TRANSACTION_BEGIN";
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS";
export const GET_TRANSACTION_ERROR = "GET_TRANSACTION_ERROR";

export const GET_SINGLE_INVENTORY_BEGIN = "GET_SINGLE_INVENTORY_BEGIN";
export const GET_SINGLE_INVENTORY_SUCCESS = "GET_SINGLE_INVENTORY_SUCCESS";

export const ADD_TRANSACTION_BEGIN = "ADD_TRANSACTION_BEGIN";
export const ADD_TRANSACTION_SUCCESS = "ADD_TRANSACTION_SUCCESS";

export const FILTER_INVENTORIES = "FILTER_INVENTORIES";
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSED = "SIDEBAR_CLOSED";

export const LOGOUT = "LOGOUT";

export const NOT_ENOUGH_PRODUCT = "NOT_ENOUGH_PRODUCT";
